{{- if (include "kubeflow.pipelines.profileController.enabled" . | eq "true") -}}

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kubeflow.pipelines.profileController.labels" . | nindent 4 }}
  name: {{ include "kubeflow.pipelines.profileController.svc.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080

{{- end }}