{{- if (include "kubeflow.pipelines.enabled" .) -}}

# TODO: integrate argo wf with minio

# TODO: figure out objectstore secret parametrization
kind: Secret
apiVersion: v1
metadata:
  labels:
    {{- include "kubeflow.pipelines.labels" . | nindent 4 }}
#   name: minio-secret
  name: mlpipeline-minio-artifact
  namespace: {{ include "kubeflow.namespace" . }}
stringData:
  accesskey: {{ .Values.pipelines.config.objectStoreAccessKey | quote }}
  secretkey: {{ .Values.pipelines.config.objectStoreSecretKey | quote }}

{{- end }}