{{- if (include "kubeflow.pipelines.enabled" .) -}}

# NOTE: this is a fallback service, it's name is hardcoded somewhere.
# TODO: figure out where is the parametrization for this Service.

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kubeflow.pipelines.labels" . | nindent 4 }}
  name: minio-service
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  ports:
  - name: minio-api
    port: 9000
    protocol: TCP
    targetPort: minio-api
  selector:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  sessionAffinity: None
  type: ClusterIP

{{- end }}
