{{- if (include "kubeflow.pipelines.ui.createIstioIntegrationObjects" .) -}}

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    {{- include "kubeflow.pipelines.ui.labels" . | nindent 4 }}
  name: {{ include "kubeflow.pipelines.ui.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "kubeflow.pipelines.ui.selectorLabels" . | nindent 6 }}
  rules:
  - from:
    - source:
        namespaces:
        - {{ .Values.istioIntegration.ingressGatewayNamespace }}

{{- end }}