apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    deployed-by: romanok1
  name: oauth2-proxy
  namespace: argocd
spec:
  destination:
    namespace: oauth2-proxy
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 6.23.1
    helm:
      values: |-
        extraArgs:
          - --skip-jwt-bearer-tokens=true
          - --extra-jwt-issuers=https://kubernetes.default.svc.cluster.local=https://kubernetes.default.svc.cluster.local
          - --set-xauthrequest=true
          - --set-authorization-header=true
          - --code-challenge-method=S256

          - --provider=oidc
          - --scope=profile email groups openid
          - --oidc-issuer-url=http://dex.dex.svc.cluster.local:5556/dex
          - --skip-oidc-discovery=true
          - --login-url=/dex/auth
          - --redeem-url=http://dex.dex.svc.cluster.local:5556/dex/token
          - --oidc-jwks-url=http://dex.dex.svc.cluster.local:5556/dex/keys
          - --skip-auth-route=/dex/.*
          - --skip-provider-button=true # go directly to the configured provider

          - --cookie-name=oauth2_proxy_kubeflow_helm
          - --cookie-expire=24h
          - --cookie-refresh=1h

          - --ssl-insecure-skip-verify=true # has to be set for kubernetes self-signed issuer

          - --upstream=static://200 # without this the authenticated requests are getting 404

          - --redirect-url=/oauth2/callback

          # not available until new oauth2-proxy release
          # Until this is not available, the dex.config.staticClients.redirectURIs has to be absolute URIs
          # - --relative-redirect-url
        
        config:
          clientID: kubeflow-oidc-authservice
          clientSecret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
          cookieSecret: XXXXXXXXXXXXXXXX

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5
    syncOptions:
    - CreateNamespace=true