apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    deployed-by: romanok1
  name: kubeflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kromanow94/kubeflow-manifests.git
    targetRevision: helmcharts
    path: charts/kubeflow
    helm:
      values: |
        istioIntegration:
          m2m:
            inCluster: true
            selfSigned:
              autoJwksDiscovery: true

        pipelines:
          cache:
            enabled: false
          mlPipeline:
            enabled: true
          persistenceAgent:
            enabled: true
          scheduledWorkflow:
            enabled: true
          ui:
            enabled: true
          viewerCrd:
            enabled: true
          metadataWriter:
            enabled: true
          metadataEnvoy:
            enabled: true
          metadataGrpcServer:
            enabled: true
          visualization:
            enabled: true
          profileController:
            enabled: true
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
      - /rules
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled