apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    deployed-by: romanok1
  name: argocd-ingress-alb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://code.roche.com/mlops/innersource-kubeflow/kubeflow-platform.git
    targetRevision: romanok1-networking-improvements
    path: config/argocd-ingress-alb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 5