apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: k8s-issuer-oidc
  namespace: istio-system
spec:
  jwtRules:
    - issuer: https://kubernetes.default.svc.cluster.local
      forwardOriginalToken: true
      outputClaimToHeaders:
        - claim: email
          header: x-auth-request-user
        - claim: email
          header: kubeflow-userid

---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: dex-issuer-oidc
  namespace: istio-system
spec:
  jwtRules:
    - issuer: http://dex.dex.svc.cluster.local:5556/dex
      forwardOriginalToken: true
      outputClaimToHeaders:
        - claim: email
          header: x-auth-request-user
        - claim: email
          header: kubeflow-userid
