images:
  tag: v3.3.10

controller:
  containerRuntimeExecutor: emissary
  persistence:
    archive: true
    archiveTTL: 90d
    connectionPool:
      connMaxLifetime: 0s
      maxIdleConns: 100
      maxOpenConns: 0
    mysql:
      database: argo
      host: mysql
      port: 3306
      tableName: argo_workflows
      passwordSecret:
        name: db-credentials
        key: mysql-root-password
      userNameSecret:
        name: db-credentials
        key: username
    nodeStatusOffLoad: true

server:
  enabled: false

useDefaultArtifactRepo: true

artifactRepository:
  archiveLogs: true
  s3:
    accessKeySecret:
      name: mlpipeline-minio-artifact
      key: accesskey
    secretKeySecret:
      name: mlpipeline-minio-artifact
      key: secretkey
    bucket: mlpipeline
    # endpoint: minio-service.kubeflow:9000
    endpoint: minio.kubeflow:9000
    insecure: true
    keyFormat: artifacts/{{workflow.namespace}}/{{workflow.name}}/{{workflow.creationTimestamp.Y}}-{{workflow.creationTimestamp.m}}-{{workflow.creationTimestamp.d}}/{{pod.name}}
