{{- if (include "kubeflow.pipelines.metadataGrpcServer.enabled" . | eq "true") -}}

{{- $autoscalingEnabled := include "kubeflow.pipelines.metadataGrpcServer.autoscaling.enabled" . -}}
{{- $replicas := include "kubeflow.pipelines.metadataGrpcServer.autoscaling.minReplicas" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "kubeflow.pipelines.metadataGrpcServer.labels" . | nindent 4 }}
  name: {{ include "kubeflow.pipelines.metadataGrpcServer.name" . }}
  namespace: {{ include "kubeflow.namespace" . }}
spec:
  {{- if (eq $autoscalingEnabled "false") }}
  replicas: {{ $replicas }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "kubeflow.pipelines.metadataGrpcServer.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "kubeflow.pipelines.metadataGrpcServer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: metadata-grpc-server
        image: {{ include "kubeflow.pipelines.metadataGrpcServer.image" . }}
        imagePullPolicy: {{ include "kubeflow.pipelines.metadataGrpcServer.imagePullPolicy" . }}

        env:
        - name: DBCONFIG_USER
          value: {{ .Values.pipelines.config.dbConfigUser }}
        - name: DBCONFIG_PASSWORD
          value: {{ .Values.pipelines.config.dbConfigPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.pipelines.config.mlmdDb | quote }}
        - name: MYSQL_HOST
          value: {{ .Values.pipelines.config.dbHost }}
        - name: MYSQL_PORT
          value: {{ .Values.pipelines.config.dbPort | quote }}

        command: ["/bin/metadata_store_server"]
        args:
        - --grpc_port={{ .Values.pipelines.metadataGrpcServer.service.port }}
        - --mysql_config_database=$(MYSQL_DATABASE)
        - --mysql_config_host=$(MYSQL_HOST)
        - --mysql_config_port=$(MYSQL_PORT)
        - --mysql_config_user=$(DBCONFIG_USER)
        - --mysql_config_password=$(DBCONFIG_PASSWORD)
        - --enable_database_upgrade=true

        ports:
        - name: grpc-api
          containerPort: {{ .Values.pipelines.metadataGrpcServer.service.port }}

        livenessProbe:
          tcpSocket:
            port: grpc-api
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: grpc-api
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 2

        {{- with .Values.pipelines.metadataGrpcServer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}

        {{- with include "kubeflow.pipelines.metadataGrpcServer.containerSecurityContext" . }}
        securityContext:
          {{- . | nindent 10 }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "kubeflow.pipelines.metadataGrpcServer.serviceAccountName" . }}

      {{- with include "kubeflow.pipelines.metadataGrpcServer.nodeSelector" . }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}

      {{- with include "kubeflow.pipelines.metadataGrpcServer.tolerations" . }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}

      {{- with include "kubeflow.pipelines.metadataGrpcServer.affinity" . }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}

      {{- with include "kubeflow.pipelines.metadataGrpcServer.topologySpreadConstraints" . }}
      topologySpreadConstraints:
        {{- . | nindent 8 }}
      {{- end }}

{{- end }}