{{- if (include "kubeflow.notebooks.controller.rbac.createRoles" . | eq "true") -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.notebooks.controller.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.kubeflow-roles.adminRoleName" . }}: "true"
  name: {{ include "kubeflow.notebooks.controller.kfNbAdminClusterRoleName" . }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-kubeflow-notebooks-admin: "true"
      rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.notebooks.controller.kfNbAdminClusterRoleName" . }}: "true"
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.notebooks.controller.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.kubeflow-roles.editRoleName" . }}: "true"
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.notebooks.controller.kfNbAdminClusterRoleName" . }}: "true"
  name: {{ include "kubeflow.notebooks.controller.kfNbEditClusterRoleName" . }}
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.notebooks.controller.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.kubeflow-roles.viewRoleName" . }}: "true"
  name: {{ include "kubeflow.notebooks.controller.kfNbViewClusterRoleName" . }}
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  - notebooks/status
  verbs:
  - get
  - list
  - watch

{{- end }}