nameOverride: ""

plugins:
# - kind: AwsIamForServiceAccount
#   spec:
#     awsIamRole: arn:aws:iam::account-id:role/s3-reader

owner:
  # kind: User
  # name: test-user@kubeflow.org
  
istioIntegration:
  enabled: true
  envoyExtAuthzHttpExtensionProviderName: oauth2-proxy