# NOTE: IMPORTANT
# We need to separate out actual rules from aggregation rules due to
# https://github.com/kubernetes/kubernetes/issues/65171
# TL;DR: We can't have both aggregation and rules in a [Cluster]Role. When that
# is the case, the rules get ignored.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.kubeflow-roles.labels" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowEditRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.kubeflow-roles.kubeflowPipelinesEditRoleName" . }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      {{- include "kubeflow.kubeflow-roles.kubeflowPipelinesEditRoleLabel" . | nindent 6 }}
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.kubeflow-roles.labels" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowPipelinesEditRoleLabel" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowViewRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.kubeflow-roles.kubeflowPipelinesViewRoleName" . }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      {{- include "kubeflow.kubeflow-roles.kubeflowPipelinesViewRoleLabel" . | nindent 6 }}
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.kubeflow-roles.labels" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowPipelinesEditRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.kubeflow-roles.aggregateToKubeflowPipelinesEditRoleName" . }}
rules:
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - pipelines
  - pipelines/versions
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - experiments
  verbs:
  - archive
  - create
  - delete
  - unarchive
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs
  verbs:
  - archive
  - create
  - delete
  - retry
  - terminate
  - unarchive
  - reportMetrics
  - readArtifact
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - jobs
  verbs:
  - create
  - delete
  - disable
  - enable
- apiGroups:
  - kubeflow.org
  verbs:
  - '*'
  resources:
  - scheduledworkflows
- apiGroups:
  - argoproj.io
  verbs:
  - '*'
  resources:
  - cronworkflows
  - cronworkflows/finalizers
  - workflows
  - workflows/finalizers
  - workfloweventbindings
  - workflowtemplates

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.kubeflow-roles.labels" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowPipelinesViewRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.kubeflow-roles.aggregateToKubeflowPipelinesViewRoleName" . }}
rules:
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - pipelines
  - pipelines/versions
  - experiments
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - runs
  verbs:
  - get
  - list
  - readArtifact
- apiGroups:
  - kubeflow.org
  resources:
  - viewers
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - visualizations
  verbs:
  - create
