{{- if (include "kubeflow.pipelines.viewerCrd.rbac.createRoles" . | eq "true") -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "kubeflow.pipelines.viewerCrd.labels" . | nindent 4 }}
  name: {{ include "kubeflow.pipelines.viewerCrd.roleBindingName" . }}
  namespace: {{ include "kubeflow.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubeflow.pipelines.viewerCrd.roleName" . }}
subjects:
- kind: ServiceAccount
  name:  {{ include "kubeflow.pipelines.viewerCrd.serviceAccountName" . }}
  namespace: {{ include "kubeflow.namespace" . }}

{{- end }}