{{- if .Values.istioIntegration.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.istio-integration.labels" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowAdminRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.istio-integration.istioAdminRoleName" . }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      {{- include "kubeflow.istio-integration.istioAdminRoleLabel" . | nindent 6 }}
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.istio-integration.labels" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowEditRoleLabel" . | nindent 4 }}
    {{- include "kubeflow.istio-integration.istioAdminRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.istio-integration.istioEditRoleName" . }}
rules:
- apiGroups: 
  - istio.io
  - networking.istio.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.istio-integration.labels" . | nindent 4 }}
    {{- include "kubeflow.kubeflow-roles.kubeflowViewRoleLabel" . | nindent 4 }}
  name: {{ include "kubeflow.istio-integration.istioViewRoleName" . }}
rules:
- apiGroups:
  - istio.io
  - networking.istio.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch

{{- end }}