{{- if (include "kubeflow.istioIntegration.m2m.inCluster" . | eq "true") -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubeflow.istioIntegration.labels" . | nindent 4 }}
  name: {{ include "kubeflow.istioIntegration.m2m.selfSigned.inClusterClusterRoleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated

{{- end }}