{{- if .Values.istioIntegration.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.istio-integration.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.kubeflow-roles.adminRoleName" . }}: "true"
  name: {{ include "kubeflow.istio-integration.istioAdminRoleName" . }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.istio-integration.istioAdminRoleName" . }}: "true"
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.istio-integration.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.kubeflow-roles.editRoleName" . }}: "true"
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.istio-integration.istioAdminRoleName" . }}: "true"
  name: {{ include "kubeflow.istio-integration.istioEditRoleName" . }}
rules:
- apiGroups: 
  - istio.io
  - networking.istio.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kubeflow.istio-integration.labels" . | nindent 4 }}
    rbac.authorization.kubeflow.org/aggregate-to-{{ include "kubeflow.kubeflow-roles.viewRoleName" . }}: "true"
  name: {{ include "kubeflow.istio-integration.istioViewRoleName" . }}
rules:
- apiGroups:
  - istio.io
  - networking.istio.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch

{{- end }}