{{- if (include "kubeflow.istioIntegration.m2m.selfSigned.autoJwksDiscovery" . | eq "true") -}}

# This is not yet fully supported.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubeflow-m2m-oidc-configurator
  namespace: istio-system
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        metadata:
          labels: {}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: self-signed-kubernetes-oidc-issuer-configurator
          containers:
            - image: curlimages/curl
              name: configure-kubernetes-oidc-issuer-jwks-in-requestauthentication
              command:
                - /script.sh
              envFrom:
                - configMapRef:
                    name: configure-self-signed-kubernetes-oidc-issuer-envs
              volumeMounts:
                - mountPath: /script.sh
                  name: script
                  subPath: script.sh
              resources: {}
          volumes:
            - name: script
              configMap:
                name: configure-self-signed-kubernetes-oidc-issuer-script
                defaultMode: 0777
                items:
                  - key: script.sh
                    path: script.sh

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-signed-kubernetes-oidc-issuer-configurator
  namespace: istio-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: self-signed-kubernetes-oidc-issuer-configurator
  namespace: istio-system
rules:
  - apiGroups:
      - security.istio.io
    resources:
      - requestauthentications
    verbs:
      - get
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: self-signed-kubernetes-oidc-issuer-configurator
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: self-signed-kubernetes-oidc-issuer-configurator
subjects:
  - kind: ServiceAccount
    name: self-signed-kubernetes-oidc-issuer-configurator
    namespace: istio-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configure-self-signed-kubernetes-oidc-issuer-envs
  namespace: istio-system
data:
  ISTIO_ROOT_NAMESPACE: istio-system
  REQUEST_AUTHENTICATION_NAME: {{ include "kubeflow.istioIntegration.m2m.requestAuthenticationName" . }}
  KUBERNETES_API_SERVER_URL: https://kubernetes.default.svc

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configure-self-signed-kubernetes-oidc-issuer-script
  namespace: istio-system
data:
  script.sh: |
    #!/bin/sh
    set -e

    KUBERNETES_API_SERVER_URL="${KUBERNETES_API_SERVER_URL:-https://kubernetes.default.svc}"
    ISTIO_ROOT_NAMESPACE="${ISTIO_ROOT_NAMESPACE:-istio-system}"
    REQUEST_AUTHENTICATION_NAME="${REQUEST_AUTHENTICATION_NAME:-{{ include "kubeflow.istioIntegration.m2m.requestAuthenticationName" . }}}"

    RESOURCE_URL="\
    ${KUBERNETES_API_SERVER_URL}\
    /apis/security.istio.io/v1/namespaces/\
    ${ISTIO_ROOT_NAMESPACE}\
    /requestauthentications/\
    ${REQUEST_AUTHENTICATION_NAME}"

    echo "Wait until resource RequestAuthentication ${REQUEST_AUTHENTICATION_NAME} in namespace ${ISTIO_ROOT_NAMESPACE} is ready."
    while true; do
      response="$(
        curl -s -o /dev/null \
          --url "${RESOURCE_URL}" \
          -w "%{http_code}" \
          --header "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" \
          --insecure
      )"
      if [ "${response}" = "200" ]; then
        break
      fi
      echo "Resource RequestAuthentication ${REQUEST_AUTHENTICATION_NAME} in namespace ${ISTIO_ROOT_NAMESPACE} is not ready yet."
      sleep 5
    done
    echo "Resource RequestAuthentication ${REQUEST_AUTHENTICATION_NAME} in namespace ${ISTIO_ROOT_NAMESPACE} is ready."

    # Get Issuer URL configured in RequestAuthentication.
    ISSUER_URL="$(
      curl -s --request GET \
        --url "${RESOURCE_URL}" \
        --header "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" \
        --insecure |
        awk -F'"' '/"issuer":/ { print $4 }'
    )"
    echo "ISSUER_URL: ${ISSUER_URL}."

    # GET URI to the JWKS.
    JWKS_URI="$(
      curl -s --request GET \
        --url "${ISSUER_URL}/.well-known/openid-configuration" \
        --header "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" \
        --insecure |
        grep -o '"jwks_uri":"https:\/\/[^"]\+"' |
        sed 's/"jwks_uri":"\(.*\)"/\1/'
    )"
    echo "JWKS_URI: ${JWKS_URI}."

    # Get content of the JWKS.
    JWKS="$(
      curl -s --request GET \
        --url "${JWKS_URI}" \
        --header "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" \
        --insecure
    )"
    echo "JWKS: ${JWKS}."

    # Format JWKS in a way that can be accepted in resource patch.
    JWKS_ESCAPED="$(echo "${JWKS}" | sed 's/"/\\"/g')"

    # Patch the RequestAuthentication with JWKS.
    curl -s --request PATCH \
      --url "${RESOURCE_URL}" \
      --header "Content-Type: application/json-patch+json" \
      --header "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" \
      -d '[{ "op": "add", "path": "/spec/jwtRules/0/jwks", "value": "'"${JWKS_ESCAPED}"'" }]' \
      --insecure

{{- end }}