{{- if (include "kubeflow.istioIntegration.enabled" . | eq "true") -}}

apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  labels:
    {{- include "kubeflow.istioIntegration.labels" . | nindent 4 }}
  name: {{ include "kubeflow.istioIntegration.userAuth.requestAuthenticationName" . }}
  namespace: {{ .Values.istioIntegration.rootNamespace }}
spec:
  jwtRules:
    - issuer: {{ .Values.istioIntegration.userAuth.issuer }}
      forwardOriginalToken: true
      outputClaimToHeaders:
        - claim: {{ .Values.istioIntegration.userAuth.userClaim }}
          header: {{ .Values.auth.userHeaderName }}

{{- end }}